### ISSUE TITLE
Create support for modules (Base library)

### ISSUE THREAD

**Issue by Rutherther** [ctu-fee-group/Christofel#2]
We will be using modules architecture for the app. There will be base library that will contain essential stuff and next to it there will be modules. Modules will be loaded dynamically, they can be reattached or detached completely.

This feature should use `Assembly.Load` and then by using reflection we should find a class that implements IModule.

Consider whether modules can communicate with each other, if some kind of library could be shared (possibly another shared library that will be loaded by either of the modules).

Modules list should be in a folder to try to load them when starting the bot so it does not have to be done manually.

Modules that should be in the app:
- Base (application) module (module that will have main function in it, it will start the bot and start loading another modules, it will contain commands for loading modules)
- API module (for GraphQL API that will be used from the frontend)
- Management module (commands for moderators)
- Messages module (sending messages, embeds, editing them)

The basic library should contain:
- Working with the bot
- Basic database (user data, roles data)
- Working with modules (interface, loading, detaching, attaching)
- Data access objects for read-only and read-and-write sharing the same interface, but read-only will throw error on write (only modules that request write will have write permissions)
- Bot shared state (discord bot app, database context, data access objects)
  - This state will be given to other modules

Each module should have custom database if it needs inner state. Read-only access will be given to each module for base database, if the module has flag for writing, then it should also get read state

**Comment by adamijak** [comment]
Each module should have independent log, so we can easily debug module.
